wandb_version: 1

init_weights_wandb_artifact:
  desc: null
  value: ''
img_res:
  desc: null
  value: 256
n_res_blocks:
  desc: null
  value: 9
patch_size:
  desc: null
  value: 70
patchgan_strides:
  desc: null
  value: 64
disc_noise_std:
  desc: null
  value: 0.2
gan_loss_fn:
  desc: null
  value: bce
lambda:
  desc: null
  value: 10
pool_size:
  desc: null
  value: 50
num_epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 1
disc_lr:
  desc: null
  value: 0.0002
gen_lr:
  desc: null
  value: 0.0002
load_weights_gen:
  desc: null
  value: 'no'
load_weights_disc:
  desc: null
  value: 'no'
gen_training_only:
  desc: null
  value: 'no'
_wandb:
  desc: null
  value:
    code_path: code/train.py
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705417319.846944
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 3
      - 16
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
